// src/components/EmotionButtons/EmotionButtons.svelte
<script lang="ts">
  import emotionsJson from '../../assets/emotions.json';
  import type { Emotion } from '../../utilities/Interfaces';
  import './EmotionButtons.scss';

  type Props = {
    selectedEmotion: string;
    disableKeyBindings: boolean;
    onSelectEmotion: (emotion: string) => void;
  };

  const emotions = emotionsJson as Emotion[];

  let { selectedEmotion, disableKeyBindings, onSelectEmotion }: Props = $props();

  let isMobile = $state(false);
  let currentEmotionIndex = $state(3);

  function selectEmotion(forward: boolean): void {
    const nextIndex = (currentEmotionIndex + (forward ? 1 : -1) + emotions.length) % emotions.length;
    const emotion = emotions[nextIndex];

    currentEmotionIndex = nextIndex;

    if (emotion) {
      onSelectEmotion(emotion.name);
    }
  }

  function selectEmotionByName(emotionName: string): void {
    const emotionIndex = emotions.findIndex((emotion) => emotion.name === emotionName);

    if (emotionIndex !== -1) {
      currentEmotionIndex = emotionIndex;
      onSelectEmotion(emotionName);
    }
  }

  $effect(() => {
    function handleResize(): void {
      isMobile = window.innerWidth <= 768;
    }

    window.addEventListener('resize', handleResize);
    handleResize();

    return () => window.removeEventListener('resize', handleResize);
  });

  $effect(() => {
    if (disableKeyBindings) return;

    function handleKeydown(event: KeyboardEvent): void {
      const key = event.key.toLowerCase();

      if (key === 'w') {
        selectEmotion(true);
      } else if (key === 's') {
        selectEmotion(false);
      }
    }

    window.addEventListener('keydown', handleKeydown);
    return () => window.removeEventListener('keydown', handleKeydown);
  });
</script>

<div class="emotion-buttons" id="character-click-target">
  {#if isMobile}
    <div class="responsive">
      <button type="button" onclick={() => selectEmotion(false)}>&#8249;</button>
      <div class="selected-emoji">{emotions[currentEmotionIndex]?.emoji}</div>
      <button type="button" onclick={() => selectEmotion(true)}>&#8250;</button>
    </div>
  {:else}
    {#each emotions as emotion (emotion.name)}
      <button
        type="button"
        class:selected={selectedEmotion === emotion.name}
        onclick={() => selectEmotionByName(emotion.name)}
      >
        {emotion.emoji}
      </button>
    {/each}
  {/if}
</div>

// src/components/EmotionButtons/EmotionButtons.tsx
/*
<--------------- Imports --------------->
*/

import React, { useState, useEffect } from "react";
import { EmotionButtonsProps } from "../../utilities/Interfaces";
import { useKeyboardContext } from "../../utilities/KeyboardContext";
import emotions from "../../assets/emotions.json";
import "./EmotionButtons.scss";

/*
<--------------- Component --------------->
*/

const EmotionButtons: React.FC<EmotionButtonsProps> = ({
  selectedEmotion,
  setSelectedEmotion,
}) => {
  /*
  <--------------- States and Variable --------------->
  */

  const [isMobile, setIsMobile] = useState<boolean>(false);
  const [currentEmotionIndex, setCurrentEmotionIndex] = useState<number>(3);

  const { disableKeyBindings } = useKeyboardContext();

  /*
  <--------------- Function --------------->
  */

  const selectEmotion = (forward: boolean) => {
    const nextIndex =
      (currentEmotionIndex + (forward ? 1 : -1) + emotions.length) %
      emotions.length;
    setCurrentEmotionIndex(nextIndex);
    setSelectedEmotion(emotions[nextIndex].name);
  };

  /*
  <--------------- useEffect Hooks --------------->
  */

  useEffect(() => {
    const handleResize = () => {
      setIsMobile(window.innerWidth <= 768);
    };

    window.addEventListener("resize", handleResize);
    handleResize();

    return () => window.removeEventListener("resize", handleResize);
  }, []);

  useEffect(() => {
    if (!disableKeyBindings) {
      const handleKeyDown = (event: KeyboardEvent) => {
        const key = event.key.toLowerCase();
        key === "w" ? selectEmotion(true) : key === "s" && selectEmotion(false);
      };

      window.addEventListener("keydown", handleKeyDown);

      return () => window.removeEventListener("keydown", handleKeyDown);
    }
  }, [selectEmotion]);

  /*
  <--------------- Rendering --------------->
  */

  return (
    <div className="emotion-buttons" id="character-click-target">
      {isMobile ? (
        <div className="responsive">
          <button onClick={() => selectEmotion(false)}>&#8249;</button>
          <div className="selected-emoji">
            {emotions[currentEmotionIndex].emoji}
          </div>
          <button onClick={() => selectEmotion(true)}>&#8250;</button>
        </div>
      ) : (
        emotions.map((emotion) => (
          <button
            key={emotion.name}
            onClick={() => {
              const emotionIndex = emotions.findIndex(
                (e) => e.name === emotion.name
              );
              setCurrentEmotionIndex(emotionIndex);
              setSelectedEmotion(emotion.name);
            }}
            className={selectedEmotion === emotion.name ? "selected" : ""}
          >
            {emotion.emoji}
          </button>
        ))
      )}
    </div>
  );
};

export default EmotionButtons;
