// src/components/CharacterSelection/CharacterSelection.tsx
/*
<--------------- Imports and Interface --------------->
*/

import React from "react";
import { Character, categories } from "../../utilities";
import characters from "../../assets/characters.json";
import "./CharacterSelection.scss";

interface CharacterSelectionProps {
  selectedCharacter: Character | null;
  selectedCategory: string;
  setSelectedCharacter: (character: Character) => void;
  setSelectedCategory: (category: string) => void;
}

/*
<--------------- Component --------------->
*/

const CharacterSelection: React.FC<CharacterSelectionProps> = ({
  selectedCharacter,
  selectedCategory,
  setSelectedCharacter,
  setSelectedCategory,
}) => {
  /*
  <--------------- Variable --------------->
  */

  const filteredCharacters =
    selectedCategory === "All"
      ? characters
      : characters.filter(
          (character) => character.category === selectedCategory
        );

  /*
  <--------------- Functions --------------->
  */

  const handleCharacterSelection = (
    event: React.ChangeEvent<HTMLSelectElement>
  ) => {
    const selectedCharId = event.target.value;
    if (selectedCharId !== "") {
      const selectedCharacter = characters.find(
        (character) => character.charId === selectedCharId
      );
      if (selectedCharacter) {
        setSelectedCharacter(selectedCharacter);
      }
    }

    event.target.blur();
  };

  const handleCategorySelection = (
    event: React.ChangeEvent<HTMLSelectElement>
  ) => {
    const selectedCategory = event.target.value;
    setSelectedCategory(selectedCategory);

    const firstCharacter =
      selectedCategory === "All"
        ? characters[0]
        : characters.find(
            (character) => character.category === selectedCategory
          );

    if (firstCharacter) {
      setSelectedCharacter(firstCharacter);
    }

    event.target.blur();
  };

  /*
  <--------------- Rendering --------------->
  */

  return (
    <div className="character-selection">
      <div className="select-block">
        <label htmlFor="category-dropdown">Category:</label>
        <select
          id="category-dropdown"
          value={selectedCategory}
          onChange={handleCategorySelection}
        >
          {categories.map((category) => (
            <option key={category} value={category}>
              {category}
            </option>
          ))}
        </select>
      </div>

      <div className="select-block">
        <label htmlFor="character-dropdown">Character:</label>
        <select
          id="character-dropdown"
          value={selectedCharacter?.charId || ""}
          onChange={handleCharacterSelection}
        >
          {filteredCharacters.map(({ charId, name }: Character) => (
            <option key={charId} value={charId}>
              {name}
            </option>
          ))}
        </select>
      </div>
    </div>
  );
};

export default CharacterSelection;

// src/components/CharacterSelection/CharacterSelection.svelte
<script lang="ts">
  import charactersJson from '../../assets/characters.json';
  import categoriesJson from '../../assets/categories.json';
  import type { Character } from '../../utilities/Interfaces';
  import './CharacterSelection.scss';

  type Props = {
    selectedCategory: string;
    selectedCharacter: Character;
    onSelectCategory: (category: string) => void;
    onSelectCharacter: (character: Character) => void;
  };

  const characters = charactersJson as Character[];
  const categories = categoriesJson as string[];

  let { selectedCategory, selectedCharacter, onSelectCategory, onSelectCharacter }: Props = $props();

  let filteredCharacters = $derived(
    selectedCategory === 'All'
      ? characters
      : characters.filter((character) => character.category === selectedCategory)
  );

  function handleCharacterSelection(event: Event): void {
    const select = event.currentTarget as HTMLSelectElement;
    const selectedCharId = select.value;
    const character = characters.find((item) => item.charId === selectedCharId);

    if (character) {
      onSelectCharacter(character);
    }

    select.blur();
  }

  function handleCategorySelection(event: Event): void {
    const select = event.currentTarget as HTMLSelectElement;
    const category = select.value;
    const firstCharacter =
      category === 'All' ? characters[0] : characters.find((character) => character.category === category);

    onSelectCategory(category);

    if (firstCharacter) {
      onSelectCharacter(firstCharacter);
    }

    select.blur();
  }
</script>

<div class="character-selection">
  <div class="select-block">
    <label for="category-dropdown">Category:</label>
    <select id="category-dropdown" value={selectedCategory} onchange={handleCategorySelection}>
      {#each categories as category (category)}
        <option value={category}>{category}</option>
      {/each}
    </select>
  </div>

  <div class="select-block">
    <label for="character-dropdown">Character:</label>
    <select id="character-dropdown" value={selectedCharacter.charId} onchange={handleCharacterSelection}>
      {#each filteredCharacters as character (character.charId)}
        <option value={character.charId}>{character.name}</option>
      {/each}
    </select>
  </div>
</div>
