// src/components/PortraitDisplay/PortraitDisplay.svelte
<script lang="ts">
  import charactersJson from '../../assets/characters.json';
  import emotionsJson from '../../assets/emotions.json';
  import type { Character, Emotion } from '../../utilities/Interfaces';
  import { getNextCharacter, getPreviousCharacter } from './PortraitDisplayUtils';
  import './PortraitDisplay.scss';

  type Props = {
    selectedCategory: string;
    selectedCharacter: Character;
    selectedEmotion: string;
    disableKeyBindings: boolean;
    onSelectCharacter: (character: Character) => void;
  };

  const characters = charactersJson as Character[];
  const emotions = emotionsJson as Emotion[];
  const portraitCache: Record<string, HTMLImageElement> = {};

  let {
    selectedCategory,
    selectedCharacter,
    selectedEmotion,
    disableKeyBindings,
    onSelectCharacter
  }: Props = $props();

  let isMobile = $state(false);
  let isPortraitsLoaded = $state(false);
  let previousCharacter = $derived(getPreviousCharacter(selectedCharacter, selectedCategory));
  let nextCharacter = $derived(getNextCharacter(selectedCharacter, selectedCategory));

  function handleNextCharacter(): void {
    onSelectCharacter(getNextCharacter(selectedCharacter, selectedCategory));
  }

  function handlePreviousCharacter(): void {
    onSelectCharacter(getPreviousCharacter(selectedCharacter, selectedCategory));
  }

  function preloadCharacterEmotionImages(characterId: string): Promise<PromiseSettledResult<void>[]> {
    const characterFolder = `/characters/${characterId}/`;

    const promises = emotions.map((emotion) => {
      const image = new Image();
      image.src = `${characterFolder}${characterId}-${emotion.name}.webp`;

      return new Promise<void>((resolve, reject) => {
        image.onload = () => {
          portraitCache[`${characterId}-${emotion.name}`] = image;
          resolve();
        };
        image.onerror = () => reject(new Error(`Image load failed: ${image.src}`));
      });
    });

    return Promise.allSettled(promises);
  }

  async function preloadImages(): Promise<void> {
    isPortraitsLoaded = false;

    const results = await Promise.allSettled(
      characters.map((character) => preloadCharacterEmotionImages(character.charId))
    );

    for (const result of results) {
      if (result.status === 'rejected') {
        console.warn(result.reason);
      }
    }

    isPortraitsLoaded = true;
  }

  $effect(() => {
    void preloadImages();
  });

  $effect(() => {
    function handleResize(): void {
      isMobile = window.innerWidth <= 768;
    }

    window.addEventListener('resize', handleResize);
    handleResize();

    return () => window.removeEventListener('resize', handleResize);
  });

  $effect(() => {
    if (disableKeyBindings) return;

    function handleKeydown(event: KeyboardEvent): void {
      const key = event.key.toLowerCase();

      if (key === 'a') {
        handlePreviousCharacter();
      } else if (key === 'd') {
        handleNextCharacter();
      }
    }

    window.addEventListener('keydown', handleKeydown);
    return () => window.removeEventListener('keydown', handleKeydown);
  });
</script>

<div class="portrait-display">
  {#if !isPortraitsLoaded}
    Loading...
  {:else}
    <div class="character-info">
      <h2 class="character-name">{selectedCharacter.name}</h2>
      <div class="portrait-gallery">
        {#if !isMobile}
          {#each [previousCharacter, selectedCharacter, nextCharacter] as character (character.charId)}
            {#if character.charId === selectedCharacter.charId}
              <div class="portrait-item selected">
                <a href={selectedCharacter.wikiUrl} target="_blank" rel="noopener noreferrer">
                  <img
                    src={`/characters/${character.charId}/${character.charId}-${selectedEmotion}.webp`}
                    alt={`Character portrait - ${character.name}`}
                  />
                </a>
              </div>
            {:else}
              <button type="button" class="portrait-item side" onclick={() => onSelectCharacter(character)}>
                <img
                  src={`/characters/${character.charId}/${character.charId}-neutral.webp`}
                  alt={`Character portrait - ${character.name}`}
                />
              </button>
            {/if}
          {/each}
        {:else}
          <div class="portrait-item selected">
            <a href={selectedCharacter.wikiUrl} target="_blank" rel="noopener noreferrer">
              <img
                src={`/characters/${selectedCharacter.charId}/${selectedCharacter.charId}-${selectedEmotion}.webp`}
                alt={`Character portrait - ${selectedCharacter.name}`}
              />
            </a>
          </div>
          <h2 class="character-title">{selectedCharacter.title}</h2>
          <div class="gallery-buttons">
            <button type="button" onclick={handlePreviousCharacter}>◄</button>
            <button type="button" onclick={handleNextCharacter}>►</button>
          </div>
        {/if}
      </div>
      {#if !isMobile}
        <h2 class="character-title">{selectedCharacter.title}</h2>
      {/if}
    </div>
  {/if}
</div>

// src/components/PortraitDisplay/PortraitDisplay.tsx
/*
<--------------- Imports --------------->
*/

import React, { useState, useEffect } from "react";
import PortraitDisplayRendering from "./PortraitDisplayRendering";
import { PortraitDisplayProps } from "../../utilities/Interfaces";
import { useKeyboardContext } from "../../utilities/KeyboardContext";
import characters from "../../assets/characters.json";
import emotions from "../../assets/emotions.json";

import "./PortraitDisplay.scss";

/*
<--------------- Component --------------->
*/

const PortraitDisplay: React.FC<PortraitDisplayProps> = ({
  selectedCharacter,
  selectedCategory,
  selectedEmotion,
  setSelectedCharacter,
}) => {
  /*
  <--------------- States and Variable --------------->
  */

  const [isMobile, setIsMobile] = useState<boolean>(false);
  const [isPortraitsLoaded, setIsPortraitsLoaded] = useState<boolean>(false);

  let portraitCache: { [key: string]: HTMLImageElement } = {};

  const { disableKeyBindings } = useKeyboardContext();

  /*
  <--------------- Functions --------------->
  */

  const getFilteredCharacters = () => {
    return selectedCategory === "All"
      ? characters
      : characters.filter(
          (character) => character.category === selectedCategory
        );
  };

  const getNextCharacter = () => {
    const filteredCharacters = getFilteredCharacters();
    const currentIndex = filteredCharacters.findIndex(
      (character) => character.charId === selectedCharacter?.charId
    );
    const nextIndex = (currentIndex + 1) % filteredCharacters.length;
    return filteredCharacters[nextIndex];
  };

  const getPreviousCharacter = () => {
    const filteredCharacters = getFilteredCharacters();
    const currentIndex = filteredCharacters.findIndex(
      (character) => character.charId === selectedCharacter?.charId
    );
    const previousIndex =
      (currentIndex - 1 + filteredCharacters.length) %
      filteredCharacters.length;
    return filteredCharacters[previousIndex];
  };

  const handleNextCharacter = () => {
    setSelectedCharacter(getNextCharacter());
  };

  const handlePreviousCharacter = () => {
    setSelectedCharacter(getPreviousCharacter());
  };

  /*
  <--------------- Preloading Images --------------->
  */

  const preloadCharacterEmotionImages = (characterId: string) => {
    const characterFolder = `./characters/${characterId}/`;

    const promises = emotions.map((emotion) => {
      return new Promise<void>((resolve) => {
        const image = new Image();
        image.onload = () => {
          portraitCache[`${characterId}-${emotion.name}`] = image;
          resolve();
        };
        image.src = `${characterFolder}${characterId}-${emotion.name}.webp`;
      });
    });

    return Promise.all(promises);
  };

  useEffect(() => {
    const preloadImages = async () => {
      setIsPortraitsLoaded(false);

      await Promise.all(
        characters.map((character) =>
          preloadCharacterEmotionImages(character.charId)
        )
      );

      setIsPortraitsLoaded(true);
    };

    preloadImages();
  }, []);

  /*
  <--------------- useEffect Hooks --------------->
  */

  useEffect(() => {
    const handleResize = () => {
      setIsMobile(window.innerWidth <= 768);
    };

    window.addEventListener("resize", handleResize);
    handleResize();

    return () => window.removeEventListener("resize", handleResize);
  }, []);

  useEffect(() => {
    if (!disableKeyBindings) {
      const handleKeyDown = (event: KeyboardEvent) => {
        const key = event.key.toLowerCase();

        if (key === "a") {
          handlePreviousCharacter();
        } else if (key === "d") {
          handleNextCharacter();
        }
      };

      window.addEventListener("keydown", handleKeyDown);

      return () => {
        window.removeEventListener("keydown", handleKeyDown);
      };
    }
  }, [handleNextCharacter, handlePreviousCharacter]);

  /*
  <--------------- Rendering --------------->
  */

  const previousCharacter = getPreviousCharacter();
  const nextCharacter = getNextCharacter();

  if (!isPortraitsLoaded) {
    return <div className="portrait-display">Loading...</div>;
  }

  return (
    <PortraitDisplayRendering
      isMobile={isMobile}
      previousCharacter={previousCharacter}
      selectedCharacter={selectedCharacter}
      nextCharacter={nextCharacter}
      selectedEmotion={selectedEmotion}
      setSelectedCharacter={setSelectedCharacter}
      handlePreviousCharacter={handlePreviousCharacter}
      handleNextCharacter={handleNextCharacter}
    />
  );
};

export default PortraitDisplay;
