// src/components/SearchBar/SearchBar.svelte
<script lang="ts">
  import { tick } from 'svelte';
  import charactersJson from '../../assets/characters.json';
  import type { Character } from '../../utilities/Interfaces';
  import { filterCharacters, getFilteredSuggestions } from './SearchBarUtils';
  import './SearchBar.scss';

  type Props = {
    selectedCategory: string;
    onSelectCharacter: (character: Character) => void;
    onDisableKeyBindings: (disabled: boolean) => void;
  };

  const characters = charactersJson as Character[];

  let { selectedCategory, onSelectCharacter, onDisableKeyBindings }: Props = $props();

  let query = $state('');
  let suggestions = $state<string[]>([]);
  let showSuggestions = $state(false);
  let selectedSuggestionIndex = $state(-1);

  function handleSearch(): void {
    const filteredCharacters = filterCharacters(query, selectedCategory);

    if (filteredCharacters[0]) {
      onSelectCharacter(filteredCharacters[0]);
    }
  }

  function handleInput(event: Event): void {
    const input = event.currentTarget as HTMLInputElement;

    query = input.value;
    selectedSuggestionIndex = -1;
    suggestions = getFilteredSuggestions(query, selectedCategory);
    showSuggestions = query !== '';
  }

  function selectSuggestion(suggestion: string): void {
    query = suggestion;
    showSuggestions = false;

    const character = characters.find(({ name, charId }) =>
      [name, charId].some((property) => property.toLowerCase().includes(suggestion.toLowerCase()))
    );

    onSelectCharacter(character ?? characters[0]);
  }

  async function moveSelectedSuggestion(nextIndex: number): Promise<void> {
    selectedSuggestionIndex = nextIndex;
    await tick();
    document.querySelector('.suggestions .selected')?.scrollIntoView({
      behavior: 'smooth',
      block: 'center',
      inline: 'nearest'
    });
  }

  function handleKeydown(event: KeyboardEvent): void {
    const suggestionCount = suggestions.length;

    if (event.key === 'ArrowDown' && suggestionCount > 0) {
      event.preventDefault();
      void moveSelectedSuggestion((selectedSuggestionIndex + 1) % suggestionCount);
    } else if (event.key === 'ArrowUp' && suggestionCount > 0) {
      event.preventDefault();
      void moveSelectedSuggestion((selectedSuggestionIndex - 1 + suggestionCount) % suggestionCount);
    } else if (event.key === 'Enter') {
      event.preventDefault();

      if (selectedSuggestionIndex !== -1 && suggestions[selectedSuggestionIndex]) {
        selectSuggestion(suggestions[selectedSuggestionIndex]);
      } else {
        handleSearch();
      }

      showSuggestions = false;
    }
  }

  $effect(() => {
    function handleClickOutside(event: MouseEvent): void {
      const searchBar = document.getElementById('search-bar');

      if (searchBar && event.target instanceof Node && !searchBar.contains(event.target)) {
        showSuggestions = false;
      }
    }

    document.addEventListener('mousedown', handleClickOutside);
    return () => document.removeEventListener('mousedown', handleClickOutside);
  });
</script>

<div class="search-bar" id="search-bar">
  <input
    type="text"
    placeholder="Search characters..."
    value={query}
    oninput={handleInput}
    onfocus={() => onDisableKeyBindings(true)}
    onblur={() => onDisableKeyBindings(false)}
    onkeydown={handleKeydown}
  />

  {#if showSuggestions}
    <ul class="suggestions">
      {#each suggestions as suggestion, index (`${suggestion}-${index}`)}
        <li class:selected={index === selectedSuggestionIndex}>
          <button
            type="button"
            onclick={() => selectSuggestion(suggestion)}
            onmouseenter={() => (selectedSuggestionIndex = index)}
          >
            {suggestion}
          </button>
        </li>
      {/each}
    </ul>
  {/if}

  <button type="button" onclick={handleSearch}>Search</button>
</div>

// src/components/SearchBar/SearchBar.tsx
/*
<--------------- Imports and Interface --------------->
*/

import React, {
  useState,
  useEffect,
  useRef,
  ChangeEvent,
  KeyboardEvent,
} from "react";
import { Character } from "../../utilities/utilities";
import { useKeyboardContext } from "../../utilities/KeyboardContext";
import characters from "../../assets/characters.json";
import "./SearchBar.scss";

interface SearchBarProps {
  selectedCategory: string;
  setSelectedCharacter: (character: Character) => void;
}

/*
<--------------- Component --------------->
*/

const SearchBar: React.FC<SearchBarProps> = ({
  selectedCategory,
  setSelectedCharacter,
}) => {
  /*
  <--------------- States and Variable --------------->
  */

  const [query, setQuery] = useState("");
  const [suggestions, setSuggestions] = useState<string[]>([]);
  const [showSuggestions, setShowSuggestions] = useState(false);
  const [selectedSuggestionIndex, setSelectedSuggestionIndex] =
    useState<number>(-1);

  const selectedSuggestionRef = useRef<HTMLLIElement>(null);

  const { setDisableKeyBindings } = useKeyboardContext();

  /*
  <--------------- Search Functions --------------->
  */

  const filterCharacters = (
    characters: Character[],
    query: string,
    selectedCategory: string
  ) => {
    return characters.filter(({ name, charId, category }) => {
      const isInSelectedCategory =
        selectedCategory === "All" || category === selectedCategory;
      const matchesQuery = [name, charId.toString()].some((property) =>
        property.toLowerCase().includes(query.toLowerCase())
      );
      return isInSelectedCategory && matchesQuery;
    });
  };

  const handleSearch = () => {
    const filteredCharacters = filterCharacters(
      characters,
      query,
      selectedCategory
    );

    if (filteredCharacters.length > 0) {
      setSelectedCharacter(filteredCharacters[0]);
    }
  };

  /*
  <--------------- Suggestion Functions --------------->
  */

  const handleInputChange = (e: ChangeEvent<HTMLInputElement>) => {
    const value = e.target.value;
    setQuery(value);
    setSelectedSuggestionIndex(-1);

    const filteredCharacters = filterCharacters(
      characters,
      value,
      selectedCategory
    );
    const filteredSuggestions = filteredCharacters.map(({ name }) => name);

    setSuggestions(filteredSuggestions);
    setShowSuggestions(value !== "");
  };

  const handleSuggestionClick = (suggestion: string) => {
    setQuery(suggestion);
    setShowSuggestions(false);

    const filteredCharacters = characters.filter(({ name, charId }) =>
      [name, charId.toString()].some((property) =>
        property.toLowerCase().includes(suggestion.toLowerCase())
      )
    );

    setSelectedCharacter(filteredCharacters[0] || characters[0]);
  };

  const handleSuggestionHover = (index: number) => {
    setSelectedSuggestionIndex(index);
  };

  /*
  <--------------- Keydown Functions --------------->
  */

  const handleKeyDown = (e: KeyboardEvent<HTMLInputElement>) => {
    const selectedIndex = selectedSuggestionIndex;
    const suggestionCount = suggestions.length;

    const handleArrowDown = () => {
      setSelectedSuggestionIndex((selectedIndex + 1) % suggestionCount);
      selectedSuggestionRef.current?.scrollIntoView({
        behavior: "smooth",
        block: "center",
        inline: "nearest",
      });
    };

    const handleArrowUp = () => {
      setSelectedSuggestionIndex(
        (selectedIndex - 1 + suggestionCount) % suggestionCount
      );
      selectedSuggestionRef.current?.scrollIntoView({
        behavior: "smooth",
        block: "center",
        inline: "nearest",
      });
    };

    const handleEnter = () => {
      e.preventDefault();
      if (selectedIndex !== -1) {
        handleSuggestionClick(suggestions[selectedIndex]);
      } else {
        handleSearch();
      }
      setShowSuggestions(false);
    };

    switch (e.key) {
      case "ArrowDown":
        e.preventDefault();
        handleArrowDown();
        break;
      case "ArrowUp":
        e.preventDefault();
        handleArrowUp();
        break;
      case "Enter":
        handleEnter();
        break;
      default:
        break;
    }
  };

  /*
  <--------------- Handler Functions --------------->
  */

  const handleFocus = () => {
    setDisableKeyBindings(true);
  };

  const handleBlur = () => {
    setDisableKeyBindings(false);
  };

  /*
  <--------------- useEffect Hook --------------->
  */

  useEffect(() => {
    const handleClickOutside = (event: MouseEvent) => {
      const searchBar = document.getElementById("search-bar");
      if (searchBar && !searchBar.contains(event.target as Node)) {
        setShowSuggestions(false);
      }
    };

    document.addEventListener("mousedown", handleClickOutside);
    return () => {
      document.removeEventListener("mousedown", handleClickOutside);
    };
  }, []);

  /*
  <--------------- Rendering --------------->
  */

  return (
    <div className="search-bar" id="search-bar">
      <input
        type="text"
        placeholder="Search characters..."
        value={query}
        onChange={handleInputChange}
        onFocus={handleFocus}
        onBlur={handleBlur}
        onKeyDown={handleKeyDown}
      />
      {showSuggestions && (
        <ul className="suggestions">
          {suggestions.map((suggestion, index) => (
            <li
              key={index}
              onClick={() => handleSuggestionClick(suggestion)}
              onMouseEnter={() => handleSuggestionHover(index)}
              className={index === selectedSuggestionIndex ? "selected" : ""}
              ref={
                index === selectedSuggestionIndex ? selectedSuggestionRef : null
              }
            >
              {suggestion}
            </li>
          ))}
        </ul>
      )}
      <button onClick={handleSearch}>Search</button>
    </div>
  );
};

export default SearchBar;
