// src/App.tsx
/*
<--------------- Imports --------------->
*/

import React, { useState } from "react";
import CharacterSelection from "./components/CharacterSelection/CharacterSelection";
import EmotionButtons from "./components/EmotionButtons/EmotionButtons";
import PortraitDisplay from "./components/PortraitDisplay/PortraitDisplay";
import { Character, categories, emotions } from "./utilities";
import characters from "./assets/characters.json";
import "./styles/App.scss";

/*
<--------------- Component --------------->
*/

const App: React.FC = () => {
  /*
  <--------------- States and Variables --------------->
  */

  const [selectedEmotion, setSelectedEmotion] = useState("Neutral");
  const [selectedCategory, setSelectedCategory] = useState("All");
  const [selectedCharacter, setSelectedCharacter] = useState<Character>({
    charId: "reimu",
    name: "Hakurei Reimu",
    title: "Shrine Maiden of Paradise",
    category: "Protagonists",
  });

  /*
  <--------------- Rendering --------------->
  */

  return (
    <div className="app">
      <CharacterSelection
        characters={characters}
        categories={categories}
        selectedCharacter={selectedCharacter}
        selectedCategory={selectedCategory}
        setSelectedCharacter={setSelectedCharacter}
        setSelectedCategory={setSelectedCategory}
      />
      <EmotionButtons
        emotions={emotions}
        selectedEmotion={selectedEmotion}
        setSelectedEmotion={setSelectedEmotion}
      />
      <PortraitDisplay
        characters={characters}
        selectedCharacter={selectedCharacter}
        selectedCategory={selectedCategory}
        selectedEmotion={selectedEmotion}
        setSelectedCharacter={setSelectedCharacter}
      />
    </div>
  );
};

export default App;

// src/App.svelte
<script lang="ts">
  import CharacterProfiles from './components/CharacterProfiles/CharacterProfiles.svelte';
  import CharacterSelection from './components/CharacterSelection/CharacterSelection.svelte';
  import EmotionButtons from './components/EmotionButtons/EmotionButtons.svelte';
  import PortraitDisplay from './components/PortraitDisplay/PortraitDisplay.svelte';
  import SearchBar from './components/SearchBar/SearchBar.svelte';
  import charactersJson from './assets/characters.json';
  import type { Character } from './utilities/Interfaces';
  import './styles/App.scss';

  const characters = charactersJson as Character[];
  const firstCharacter = characters[0];

  if (!firstCharacter) {
    throw new Error('No characters are available.');
  }

  let selectedCategory = $state('All');
  let selectedEmotion = $state('neutral');
  let selectedCharacter = $state<Character>(firstCharacter);
  let disableKeyBindings = $state(false);
</script>

<div class="app">
  <CharacterSelection
    {selectedCharacter}
    {selectedCategory}
    onSelectCharacter={(character) => (selectedCharacter = character)}
    onSelectCategory={(category) => (selectedCategory = category)}
  />
  <SearchBar
    {selectedCategory}
    onSelectCharacter={(character) => (selectedCharacter = character)}
    onDisableKeyBindings={(disabled) => (disableKeyBindings = disabled)}
  />
  <EmotionButtons
    {selectedEmotion}
    {disableKeyBindings}
    onSelectEmotion={(emotion) => (selectedEmotion = emotion)}
  />
  <PortraitDisplay
    {selectedCharacter}
    {selectedCategory}
    {selectedEmotion}
    {disableKeyBindings}
    onSelectCharacter={(character) => (selectedCharacter = character)}
  />
  <CharacterProfiles
    {selectedCharacter}
    {selectedCategory}
    onSelectCharacter={(character) => (selectedCharacter = character)}
  />
</div>
